version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  build:
    commands:
        - echo Uploading Artifacts to S3
        - echo $CODEBUILD_WEBHOOK_TRIGGER
artifacts:
    files: 
        - '**/*'
